services:
  # Serviço da aplicação Spring Boot
  app:
    build: .
    container_name: oficina-app
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      # Variáveis para o banco de dados
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=oficinadb
      - DB_USER=user
      - DB_PASS=password
      # Variável para o JWT (pega o valor do seu terminal)
      - JWT_SECRET=${JWT_SECRET}
      # Variáveis de E-mail (exemplo, idealmente viriam de um vault)
      - MAIL_HOST=smtp.example.com
      - MAIL_PORT=587
      - MAIL_USER=seu-email@example.com
      - MAIL_PASS=sua-senha-de-app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - oficina-net

  # Serviço do banco de dados PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: oficina-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=oficinadb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d oficinadb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - oficina-net

networks:
  oficina-net:
    driver: bridge

volumes:
  postgres_data:
