services:
  # Serviço da aplicação Spring Boot
  app:
    build: .
    container_name: oficina-app
    ports:
      - "8080:8080"  # Porta da aplicação
      - "5005:5005"  # Porta de depuração
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/oficinadb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - oficina-net

  # Serviço do banco de dados PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: oficina-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=oficinadb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d oficinadb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - oficina-net

# --- DEFINIÇÃO DA REDE (ESTA PARTE ESTAVA EM FALTA) ---
networks:
  oficina-net:
    driver: bridge

volumes:
  postgres_data:
